(* generated by dune *)

(** @canonical Interface.Choose *)
module Choose = Interface__Choose

(** @canonical Interface.Dashboard *)
module Dashboard = Interface__Dashboard

(** @canonical Interface.DataCheck *)
module DataCheck = Interface__DataCheck

(** @canonical Interface.FileWrite *)
module FileWrite = Interface__FileWrite

(** @canonical Interface.Operations *)
module Operations = Interface__Operations

(** @canonical Interface.StockPage *)
module StockPage = Interface__StockPage
